### ISSUE TITLE
Recursive close folds does not work

### ISSUE THREAD

**Issue by dlobue** [stevearc/aerial.nvim#120]
**Describe the bug**
Keybinds and commands to recursively close folds only closes the top level. This is definitely a closing issue and not an opening issue as manually folded nested structures do not open when opening the top level (as expected).

I have observed this bug in both python and yaml filetypes.

**System information**
- OS: mac & linux
- Neovim version: v0.7.0
- AerialInfo:
```
Filetype: python
Configured backends:
treesitter (supported) (attached)
lsp (not supported) [LSP client not attached]
markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct


Filetype: yaml
Configured backends:
treesitter (supported) (attached)
lsp (not supported) [LSP client not attached (did you call aerial.on_attach?)]
markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```
- Aerial config:
```lua
function() require('aerial').setup() end
```

**To Reproduce**
1. Open yaml file with code sample provided
2. Open Aerial side panel
3. Ensure all nodes are expanded
4. Press `zM`
5. Now press `zo` on the node named `one`
6. Note that all child nodes are still expanded.
7. Press `zc` while cursor is over the node named `two`
8. Close the top-level node again
9. Re-open the top-level node again, and node that the child node `two` is collapsed as expected.

If possible, provide a minimal file that will trigger the issue:
```yaml
one:
  two:
    three:
      - a
      - b
      - c
  rawr: hi
```

**Additional context**
My treesitter (and nvim) configuration is here: https://github.com/dlobue/dotvim/blob/nvim/lua/plugins/nvim-treesitter.lua

**Comment by stevearc** [comment]
Traveling at the moment. I'll look into this after this weekend

**Comment by stevearc** [comment]
This seems to be an issue with how we were handling zM and zR, and the foldlevel in general. Should hopefully be fixed now

**Comment by dlobue** [comment]
Thanks! I just tested it out and the fix does resolve the `zM` and `zR` case, however `zC`/`H` does not work properly. `zC` recursively closes from the top down, instead of bottom up. For example, given the following doc, if you were to put your cursor on the node `three` and press `zC`, the nodes `one`, `two`, and `three` would fold instead of the expected `three` and `four`.

```yaml
one:
  two:
    three:
      four:
        five: done
```

**Comment by dlobue** [comment]
I looked at the files you touched in your fix, and figured out how to fix the bug myself. I have opened up a PR here: https://github.com/stevearc/aerial.nvim/pull/123

**Comment by stevearc** [comment]
Isn't that just how folds work in vim? If I unlink the tree and folds entirely with
```lua
require('aerial').setup({
    link_folds_to_tree = false,
    link_tree_to_folds = false,
    manage_folds = true,
})
```
and then put my cursor on `three:` and do `zC`, it folds `one`, `two`, and `three`.

**Comment by dlobue** [comment]
wow... my bad, you are correct. I verified that this is the default vim functionality using the following test data:
```yaml
aone:
  atwo:
    athree:
      afour:
        afive:
          asix:
            aseven:
              aeight:
                anine:
                  aten: done
bone:
  btwo:
    bthree:
      bfour:
        bfive:
          bsix:
            bseven:
              beight:
                bnine:
                  bten: done
```

And then running the following command to get a stock and unmodified instance of vim:
```sh
\vim -u /dev/null -S /dev/null --noplugin -c ':set foldmethod=indent foldlevel=99 expandtab sw=2' fold-test.yaml
```

Typing `zC` on node `asix` does indeed fold all parent nodes and none of the children. I'll close my PR.

Wow.. that just makes no sense in my mind. The docs literally say `Close all folds under the cursor recursively.`  How are fold parents under the cursor?

I went through the docs, tried all the other fold commands, and as far as I can tell there is no way to recursively close all child folds. The closest you can get is `zMzv`, but that operates on the entire document...

Am I missing something? Is there a way to recursively fold all child folds that I'm missing?
